name: alexkess
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22222
title: Alex Kess Photographer - Sydney
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfdfdf'
    - '#bababa'
    - '#363636'
    - '#919191'
    - '#000000'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: 'null'
    url: null
