name: alexkess
favicon: null
layout_spectrum: 0
typography_spectrum: 0.21728
title: Alex Kess Photographer - Sydney
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3a3a3a'
    - '#a1a1a1'
    - '#bebebe'
    - '#838383'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: follow
    item: 'null'
    url: null
